name: supershop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  hexcolor: ^2.0.0
  percent_indicator: ^2.1.9+1
  auto_size_text: ^2.1.0
  colorful_safe_area: ^0.2.1
  flutter_screenutil: ^4.0.3+3
  modal_bottom_sheet: ^2.0.0
  grouped_buttons: ^1.0.4
  http: ^0.13.3
  get_it: ^6.0.0
  loading_animations: "^2.1.0"
  cached_network_image: ^2.3.2+1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  dartz: ^0.9.2
  flutter_countdown_timer: ^4.1.0
  fab_circular_menu: ^1.0.1
  clipboard: ^0.1.3
  carousel_slider: ^3.0.0
  intl: ^0.17.0
  flutter_widget_from_html_core: ^0.6.1+3
  introduction_screen: ^2.1.0
  shimmer: ^2.0.0
  flutter_sms: ^2.3.1
  url_launcher: ^6.0.9
  firebase_core: ^1.3.0
  firebase_auth: ^3.0.1
  pinput: ^1.2.0
  google_sign_in: ^5.0.4
  like_button: ^2.0.2
  flutter_facebook_auth: ^3.5.0
  flutter_webview_plugin: ^0.4.0
  flutter_rating_bar: ^4.0.0
  firebase_messaging: ^10.0.4
  uni_links: ^0.5.1
  launch_review: ^3.0.1
  share_plus: ^2.1.4
  html_unescape: ^2.0.0
  youtube_player_flutter: ^8.0.0
  stacked_firebase_auth: ^0.2.10
  flutter_custom_clippers: ^2.0.0
  qr_code_scanner: ^0.5.2
  dart_ipify: ^1.1.1
  photo_view: ^0.12.0
  money2: ^2.2.1
  easy_mask: ^2.0.1
  email_validator: ^2.0.1
  country_code_picker: ^2.0.2
  pull_to_refresh: ^2.0.0
  upgrader: ^3.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/lobby/
    - images/account/
    - images/blog/
    - images/cart/
    - images/order/
    - images/product_detail/
    - images/search/
    - i18n/en.json
    - i18n/id.json
    - i18n/es.json
    - i18n/fr.json
    - i18n/zh.json
    - i18n/ja.json
    - i18n/ko.json
    - i18n/ar.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300          
        - asset: fonts/Poppins-Regular.ttf          
          weight: 400
        - asset: fonts/Poppins-Medium.ttf          
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf          
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900        


  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
